# Generated by Django 3.1.1 on 2020-09-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pl', 'pl'), ('en', 'en')], max_length=2)),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('language', models.CharField(choices=[('pl', 'pl'), ('en', 'en')], max_length=2)),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('created', models.DateField()),
                ('technologies', models.ManyToManyField(to='projects.Technology')),
            ],
            options={
                'ordering': ['order'],
                'get_latest_by': 'order',
            },
        ),
        migrations.CreateModel(
            name='LearnProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('language', models.CharField(choices=[('pl', 'pl'), ('en', 'en')], max_length=2)),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('created', models.DateField()),
                ('technologies', models.ManyToManyField(to='projects.Technology')),
            ],
            options={
                'ordering': ['order'],
                'get_latest_by': 'order',
            },
        ),
    ]
